### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-artwork#102]
Port to Python 3.

- [x] remove or port both em.py to Python 3,
- [x] port icons/import-icon to Python 3,
- [X] <s>make local Fedora and Debian packages for testing by others.</s>

_Python programs in `sugar-artwork` are used during build only._

**Comment by Pro-Panda** [comment]
Our `em.py` was the same as upstream `em.py` except for the shebang line, we had `python2` (because some distributions use python3 as default 815303c), whereas upstream had `python`
No other changes were present in `v3.3` and our current version

After the port, we should write `python3` in shebang instead of `python` since a lot of distributions still use `python2` as default. If not, then we can remove our local `em.py` files

**Comment by quozl** [comment]
As of https://github.com/sugarlabs/sugar-artwork/commit/29fc56cbbfc49af1f7c8c0930814ad174dc898f5, no other code changes are planned for _sugar-artwork_ for the Port to Python 3 project, and _sugar-artwork_ is ready to be tested using the [native build environment method](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#native-sugar), making local packages, and release.

**Comment by Aniket21mathur** [comment]
Thanks, looking forward to the release of artwork once tested. ;-)

**Comment by quozl** [comment]
Thanks.  Release won't be for a while yet.  We like to release _sugar_, _sugar-toolkit-gtk3_, _sugar-datastore_ and _sugar-artwork_ at the same time.

**Comment by Aniket21mathur** [comment]
Agreed. Thanks!
