### ISSUE TITLE
Latest distribution source package

### ISSUE THREAD

**Issue by octamois** [sugarlabs/sugar-artwork#105]
While making debian package, this came into light that using command
 

> sudo apt source sugar-artwork

extracted files are sugar-artwork-0.106.0 and our configure.ac reflects version 0.112
I'm curious about about this!

@quozl something?

**Comment by quozl** [comment]
You are observing downstream lag, because you have an old operating system installed.

Upgrade to Debian Stretch will get you Sugar 0.110.

Upgrade to Debian Sid (experimental), Debian Buster (testing), or Ubuntu Bionic 18.04 (not released) will get you Sugar 0.112.

**Comment by octamois** [comment]
It worked fine now after Upgrading to Ubuntu to Bionic.That was downstream lag.
Thank you for the help, This is solved so closing the issue.

**Comment by quozl** [comment]
Thanks.

For your interest Ubuntu Bionic Beaver entered Feature Freeze phase today, so we can expect 18.04 to ship with Sugar 0.112.  The bugs it has now will have either of these fates;

* if reported to Ubuntu, bugs may be fixed before release of 18.04, or;
* if not reported, good chance they won't be fixed by Ubuntu, and will have to be worked around by anyone who wants to deploy Sugar.  ;-)

There are some bugs listed in Debian for Sugar.  I think of these as canaries.
